### ISSUE TITLE
[FE] bug: 변경된 파일 목록엔 없지만 GitHub outdated diff에 달린 댓글이 넘어오는 문제

### ISSUE THREAD

**Issue by pigpgw** [jungle-6-3/code-sync-fe#105]
### 기능 의도
- 댓글을 클릭하면 해당 파일로 이동하여 내용을 확인할 수 있도록 구현

### 문제 발생
- 댓글 데이터에서 파일 이름을 추출해 해당 파일을 에디터에 표시하려고 할 때 **파일이 존재하지 않아 에러** 발생

### 문제 상황
- PR 리뷰 중, 리뷰어가 특정 파일에 댓글을 작성
- 이후 PR에서 리뷰어의 요청을 반영해 추가 작업을 수행하면서 **파일이 이동되거나 삭제**됨
- 현재 기능은 댓글 클릭 시 **GitHub REST API**에서 제공하는 `file changed list`를 사용해 댓글과 연결된 파일을 찾아 에디터에 표시
- 문제는 **GitHub API**가 PR의 최신 변경 상태만 반영하여, **다른 파일에 동일한 내용이 존재하는 삭제된 파일을 `file changed list`에 포함하지 않음**
- 이로 인해 **댓글 클릭 시 해당 파일이 존재하지 않아 에러** 발생

### 문제의 파일 정보
- 문제 발생 예시 ([PR 링크](https://github.com/jungle-6-3/code-sync-fe/pull/103))
- 삭제된 파일 (`SelectedFileViewer.tsx`)이 이동 또는 삭제되었지만, GitHub UI에는 표시되고, API에서는 `file changed list`에 포함되지 않음

## 발생 상황 상세
1. **최초 PR 상태**:
   - `src/components/SelectedFileViewer.tsx` 파일에 리뷰어가 코드 리뷰 댓글 작성
   - 이 댓글은 PR의 첫 번째 버전에 기록됨

2. **리뷰 후 추가 작업**:
   - 같은 PR 브랜치에서 `src/components/SelectedFileViewer.tsx` 파일을 `src/components/SelectedFile/index.tsx`로 이동
   - `index.tsx`에서 컴포넌트를 `SelectedFileViewer`로 export함
   - 기존 파일을 삭제 후 새로운 위치로 이동하며 PR #87에서 확인 가능

3. **파일 병합 충돌 해결 과정**:
   - 파일 경로와 컴포넌트 이름이 동일한 상태로 병합되면서, 같은 내용의 파일이 다른 이름으로 중복 생성됨
   - 원본 파일 `SelectedFileViewer.tsx` 삭제

## GitHub의 파일 처리 방식 특성
- GitHub는 **기존 파일의 내용을 일부 포함한 새 파일이 이동된 경우**, 이를 "이동" 또는 "리팩토링"으로 인식
- 동일 내용이 다른 위치에 존재하는 경우 `removed`로 처리하지 않고 API 응답에서 제외
- GitHub UI에서는 과거의 리뷰 맥락을 보존하기 위해 댓글을 표시하지만, **API는 최신 상태만 반영**하여 `file changed list`에 파일이 포함되지 않음

## API 응답 누락 원인
1. **파일 이동/리팩토링 인식**:
   - GitHub는 동일한 내용이 새 위치에 존재하는 경우 이를 "삭제된 파일"로 완전히 간주하지 않고, 이동된 파일로 처리

2. **GitHub API의 최신 상태 반영**:
   - GitHub API는 PR의 최종 상태만을 반영하며, 현재 존재하지 않는 파일은 `file changed list`에 포함되지 않음

## 댓글 처리 방안
1. **커밋 해시를 이용한 파일 조회**
   - 삭제된 파일의 이전 버전을 찾아 표시
   - 문제점: API 호출 증가로 rate limit 위험 및 성능 저하

2. **사용자 안내 메시지 표시 (채택)**
   - 삭제되거나 존재하지 않는 파일에 대해 명확한 안내 메시지 제공
   - "삭제되거나 존재하지 않는 경로의 파일입니다" 메시지 표시

3. **댓글 별도 영역 분리**
   - 관련 댓글들을 따로 모아서 보여주는 방식

### 관련 PR 링크
- [PR #103](https://github.com/jungle-6-3/code-sync-fe/pull/103)

### 파일이 UI에 보이는데 API로는 포함되지 않는 이유는?
GitHub UI는 과거 리뷰 맥락을 보존하기 위해 댓글을 표시하지만, API는 현재 변경된 파일 목록만 제공하여 삭제된 파일은 `file changed list`에 포함되지 않습니다.

### 삭제된 파일을 확인하는 다른 방법이 있나요?
커밋 ID를 통해 삭제되기 전 시점의 파일을 조회할 수 있지만, GitHub API 요청 횟수 제한과 비효율성으로 인해 일반적이지 않은 방식입니다.

**Comment by loopy-lim** [comment]
그러면 그냥 sha만 비교하고, outdate되었다는 이야기정도만 하죠
